font_path:
    - .
    - C:\P-ROC\shared\dmd

# Uncomment the following line to use a virtual P-ROC instead of running on real hardware.
pinproc_class: procgame.fakepinproc.FakePinPROC

config_path:
    - ~/P-ROC/shared/config

keyboard_switch_map:
    # Enter, Up, Down, Exit
    7: SD8
    8: SD7
    9: SD6
    0: SD5
    #  Start
    s: StartButton
    z: SF4
    /: SF2

dmd_cache_path: ~/.pyprocgame/dmd_cache

# Where you want your log file to go. Use "stdout" for then screen.
log_destination: ./log.text
