Custom Message: {Custom Message: Disabled, Custom Message Pages: 1, Page 1 Border: NONE,
  Page 1 Line 1 Color: WHITE, Page 1 Line 1 Justify: CENTER, Page 1 Line 1 Size: 7,
  Page 1 Line 1 Text: NONE, Page 1 Line 2 Color: WHITE, Page 1 Line 2 Justify: CENTER,
  Page 1 Line 2 Size: 7, Page 1 Line 2 Text: NONE, Page 1 Line 3 Color: WHITE, Page 1 Line 3 Justify: CENTER,
  Page 1 Line 3 Size: 7, Page 1 Line 3 Text: NONE, Page 1 Preview: 1, Page 2 Border: NONE,
  Page 2 Line 1 Color: WHITE, Page 2 Line 1 Justify: CENTER, Page 2 Line 1 Size: 7,
  Page 2 Line 1 Text: NONE, Page 2 Line 2 Color: WHITE, Page 2 Line 2 Justify: CENTER,
  Page 2 Line 2 Size: 7, Page 2 Line 2 Text: NONE, Page 2 Line 3 Color: WHITE, Page 2 Line 3 Justify: CENTER,
  Page 2 Line 3 Size: 7, Page 2 Line 3 Text: NONE, Page 2 Preview: 2, Page 3 Border: NONE,
  Page 3 Line 1 Color: WHITE, Page 3 Line 1 Justify: CENTER, Page 3 Line 1 Size: 7,
  Page 3 Line 1 Text: NONE, Page 3 Line 2 Color: WHITE, Page 3 Line 2 Justify: CENTER,
  Page 3 Line 2 Size: 7, Page 3 Line 2 Text: NONE, Page 3 Line 3 Color: WHITE, Page 3 Line 3 Justify: CENTER,
  Page 3 Line 3 Size: 7, Page 3 Line 3 Text: NONE, Page 3 Preview: 3, Page 4 Border: NONE,
  Page 4 Line 1 Color: WHITE, Page 4 Line 1 Justify: CENTER, Page 4 Line 1 Size: 7,
  Page 4 Line 1 Text: NONE, Page 4 Line 2 Color: WHITE, Page 4 Line 2 Justify: CENTER,
  Page 4 Line 2 Size: 7, Page 4 Line 2 Text: NONE, Page 4 Line 3 Color: WHITE, Page 4 Line 3 Justify: CENTER,
  Page 4 Line 3 Size: 7, Page 4 Line 3 Text: NONE, Page 4 Preview: 4, Page 5 Border: NONE,
  Page 5 Line 1 Color: WHITE, Page 5 Line 1 Justify: CENTER, Page 5 Line 1 Size: 7,
  Page 5 Line 1 Text: NONE, Page 5 Line 2 Color: WHITE, Page 5 Line 2 Justify: CENTER,
  Page 5 Line 2 Size: 7, Page 5 Line 2 Text: NONE, Page 5 Line 3 Color: WHITE, Page 5 Line 3 Justify: CENTER,
  Page 5 Line 3 Size: 7, Page 5 Line 3 Text: NONE, Page 5 Preview: 5}
Gameplay (Feature): {2X Scoring Feature: Enabled, 2X Scoring Hits: 2, 2X Scoring Timer: 30,
  Ambush Awards Badge: 'No', Ambush Ball Saver: Enabled, Ambush Escapes to Lose: 3,
  Ambush Target Timer: 12, Ambush or Showdown First: Ambush, Attract Mode Music: 'Yes',
  Attract Mode Sounds: 'Yes', Attract Mode Wind Noise: 'Yes', Attract sound delay time: 120,
  Attract sounds to play: 3, Bart Brothers Difficulty: Easy, Bart Brothers Guests: Enabled,
  Bart Brothers for Star: 3, Beer Mug Hits Boost: 3, Beer Mug Hits For Multiball: 5,
  Bionic Bart Ball Save: Enabled, Bionic Bart Ball Save Timer: 15, Bonus X Limit: Enabled,
  Bonus X Max: 5, Boss Bart Posse: Avoid, Bozo Ball: Enabled, Bozo Ball Minutes: 2,
  CVA GI Behavior: Default, Combo Timer: 7, Combos for Star: 10, Default Ball Save Time: 10,
  Drunk Multiball: Enabled, Drunk Multiball End Saver: Enabled, Drunk Multiball GI: Disabled,
  Drunk Multiball Intro Skip: 'No', Drunk Multiball Stacking: Enabled, Fast Restart After Game: Enabled,
  Franks N Beans: Enabled, Franks N Beans Time: 30, Gold Mine Bandits: Enabled, Gold Mine Bandits Timer: 30,
  Gold Mine Multiball Restart: 'Yes', Gold Mine Restart Timer: 8, Gunfight Difficulty: Easy,
  Gunfight Mountain: Brown, High Def Flair: Enabled, Last Call Mode: Enabled, Marshall Jackpot Timer: 15,
  Marshall Multiball: Enabled, Marshall Multiball Music: 'No', Marshall Req for Bionic: 'No',
  Midnight Force: Enabled, Mine Opening Difficulty: Easy, Moonlight Mins to Midnight: 3,
  Moonlight Shots at Start: 3, Motherlode Badge Difficulty: Easy, Move Your Train Max Shots: 7,
  Move Your Train Mode: Enabled, Multiball Ball Savers: 'No', Multiball Locks Difficulty: Easy,
  Multiball Savers Timer: 10, Party - Flip Count: 20, Party - Limited Flips: 50, Party Mode: Disabled,
  Polly Dies Animation: Show, Quickdraw Timer: 20, Quickdraw Wins for EB: 4, Quickdraws Lit Difficulty: Easy,
  Save Polly Shots - River: 3, Save Polly Shots - Train: 5, Save Polly Timer - Bank: 30,
  Save Polly Timer - River: 30, Save Polly Wins Required: 'No', Shots to defeat Bionic Bart: 3,
  Showdown Difficulty: Easy, Skillshot Boosts: Easy, Stampede Mode: Alternate, Super Cheat: Disabled,
  Super Skill 3 Million: Disabled, Super Skill Bonus X: Disabled, Super Skill Gunfight: Disabled,
  Super Skill Shot: Enabled, Tournament Mode: Enabled, Tribute Mode: Enabled, Tribute Selecting: Manual,
  Tumbleweeds for CVA: 3, Tumbleweeds for CVA Boost: 3}
Machine (Standard): {Autoplunger Strength: 45, Balls Per Game: 3, Color Display Dot Style: GRID,
  Color Display Pixel Size: 4, Color Display X Offset: 4, Color Display Y Offset: 4,
  Drop Target Boost: 25, Flipper Pulse: 34, Game Restart: true, Inactive Switch Warning: 0,
  Match Percentage: 10, Max Initials Length: 3, Maximum Extra Balls: 2, Mine Kicker Strength: 20,
  Real Knocker Installed: 'Yes', Real Knocker Strength: 20, Replay Auto Adjust: 'Yes',
  Replay Award: Last Call, Replay Score: 7000000, Replay Score Pad: 0, Replays: Enabled,
  Saloon Eject Strength: 30, Slow Attract Pages: Disabled, Tilt Warnings: 2, Trough Eject Strength: 30}
Sound: {Initial volume: 9, Music volume offset: 0}
